language: rust
sudo: false
rust:
# This represents the minimum Rust version supported by Tokio. Updating this
# should be done in a dedicated PR and cannot be greater than two 0.x
# releases prior to the current stable.
- 1.26.0
- stable
- beta
- nightly

script:
- cargo test --verbose -p tokio-trace-futures
- cargo test --verbose -p tokio-trace-subscriber
- cargo test --verbose -p tokio-trace-tower
# Don't test `tokio-trace-tower-http`'s examples on 1.26.0 --- they depend on
# `tower-h2` which uses the `dyn` keyword.
- cargo test -p tokio-trace-tower-http --lib --tests
- cargo test -p tokio-trace-tower-http --doc
- cargo test --verbose -p tokio-trace-log
- cargo test --verbose -p tokio-trace-env-logger
- cargo test --verbose -p tokio-trace-macros

jobs:
  include:
  # Test stage for crates which don't build on Rust 1.26.0 for unavoidable reasons.
  - stage: test
    name: "test stable only"
    script:
    - cargo test -p tokio-trace-proc-macros
    - cargo test -p tokio-trace-tower-http --examples
    rust: stable
  - script: cargo fmt --all -- --check
    install: rustup component add rustfmt-preview
    name: "rustfmt"
    rust: stable
